### ISSUE TITLE
"Xia Express a cessé de fonctionner" lors d'un clic sur "Nouvelle ressource..."

### ISSUE THREAD

**Issue by Julientroploin** [gbarre/xiaExpressAndroid#2]
Résumé du bug :
Tout est dans le titre : Android m'affiche un message "Xia Express a cessé de fonctionner" lorsque je clique sur "Nouvelle ressource..." (ou sur "Nouvelle im..." dans le top menu.

#### Étapes pour reproduire :
1. Lancer Xia
2. Cliquer sur "Nouvelle ressource..."

Device infos :
- Modèle : Nokia 6.1 (2018) TA-1043
- Version de l'API : Android 8.1.0
- Résolution utilisée :  1920 x 1080 px
- Densité de pixel : 401 ppp
- PackageName : Xia Express
- VersionCode : Version 1.0-Beta4
- VersionName : 

Informations supplémentaires : 
J'ai installé Xia express grâce à F-Droid 1.3.1
Je ne sais pas comment obtenir plus d'informations sur le bug, mais si on me guide, je reste disponible...

**Comment by gbarre** [comment]
Je n'avais pas remarqué que la release n'était pas à jour (Bêta4). Je viens de mettre la dernière version stable en release, je ne sais pas combien de temps cela va prendre pour redescendre sur F-Droid. En espérant qu'elle fonctionne sur votre device.
L'application est également disponible sur le PlayStore si vous le souhaitez : https://play.google.com/store/apps/details?id=fr.ac_versailles.dane.xiaexpress

**Comment by Julientroploin** [comment]
Je n'ai pas d'usage urgent prévu prochainement, donc j'attends la mise à jour sur F-Droid pour vous signaler lorsqu'elle arrivera et vérifier que le bug disparaît.

Merci pour la réactivité.

**Comment by Julientroploin** [comment]
Bonjour,
la mise à jour est arrivée ce matin, mais elle n'a pas réglé le bug.
Si je peux donner plus d'infos merci de me donner la marche à suivre.

**Comment by gbarre** [comment]
Bonjour,
Je suis désolé mais Xia Express ne fonctionne pas sur téléphone, c'est un choix initial que l'équipe a fait lors de son développement.

**Comment by Julientroploin** [comment]
Aucun soucis, je désinstalle. Je testerais sur tablette à l'occasion.
Peut être serait il bon d'indiquer ce choix dans la description ?
